  from cd_rbm import *  
  
  from sklearn import datasets

  digists = datasets.load_digits()
  X_train, y_train = digists.data, digists.target

  X = X_train[y_train==0]

  rbm = CDRBM(max_iter=500, mc_iter=1, persistent=False)
  # number of values taken by x, {0,1,...16}
  rbm.n_values = 17 # currently, you have to set the attr. manually.
  rbm.fit(X)

  # choose a sample
  x = X[4]
  x_ = rbm.generate(mc_iter=50)

  import matplotlib.pyplot as plt
  fig = plt.figure()
  ax = fig.subplots(1, 2)
  ax[0].imshow(x.reshape((8, 8)))
  ax[0].set_title('A real digit')
  ax[1].imshow(x_.reshape((8, 8)))
  ax[1].set_title('generated by CD')
  for _ in ax: _.set_axis_off()
  fig.suptitle("Digit Generator (Test of CD-RBM)")
  plt.show()
